# Generated by Django 2.1.3 on 2018-12-05 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('province_id', models.AutoField(primary_key=True, serialize=False)),
                ('province_name', models.CharField(blank=True, max_length=45, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='winesearch.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Region1',
            fields=[
                ('region1_id', models.AutoField(primary_key=True, serialize=False)),
                ('region1_name', models.CharField(blank=True, max_length=45, null=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='winesearch.Province')),
            ],
        ),
        migrations.CreateModel(
            name='Region2',
            fields=[
                ('region2_id', models.AutoField(primary_key=True, serialize=False)),
                ('region2_name', models.CharField(blank=True, max_length=45, null=True)),
                ('region1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='winesearch.Region1')),
            ],
        ),
        migrations.CreateModel(
            name='Taster',
            fields=[
                ('taster_id', models.AutoField(primary_key=True, serialize=False)),
                ('taster_name', models.CharField(blank=True, max_length=45, null=True)),
                ('twitter_handles', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('variety_id', models.AutoField(primary_key=True, serialize=False)),
                ('variety_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VarietyRegion1',
            fields=[
                ('variety_region1_id', models.AutoField(primary_key=True, serialize=False)),
                ('region1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='winesearch.Region1')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='winesearch.Variety')),
            ],
        ),
        migrations.CreateModel(
            name='VarietyRegion2',
            fields=[
                ('variety_region2_id', models.AutoField(primary_key=True, serialize=False)),
                ('region2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='winesearch.Region2')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='winesearch.Variety')),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('wine_id', models.AutoField(primary_key=True, serialize=False)),
                ('wine', models.CharField(max_length=45)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=45, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='winesearch.Country')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='winesearch.Province')),
                ('region1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='winesearch.Region1')),
                ('region2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='winesearch.Region2')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='winesearch.Variety')),
            ],
        ),
        migrations.CreateModel(
            name='Winery',
            fields=[
                ('winery_id', models.IntegerField(primary_key=True, serialize=False)),
                ('winery_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WineryVariety',
            fields=[
                ('winery_variety_id', models.AutoField(primary_key=True, serialize=False)),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='winesearch.Variety')),
                ('winery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='winesearch.Winery')),
            ],
        ),
        migrations.CreateModel(
            name='WineTaster',
            fields=[
                ('wine_taster_id', models.AutoField(primary_key=True, serialize=False)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('taster', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='winesearch.Taster')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='winesearch.Wine')),
            ],
        ),
        migrations.AddField(
            model_name='wine',
            name='winery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='winesearch.Winery'),
        ),
    ]
