# Generated by Django 2.1.3 on 2018-12-15 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'Country',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('province_id', models.AutoField(primary_key=True, serialize=False)),
                ('province_name', models.CharField(max_length=45)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='winesearch.Country')),
            ],
            options={
                'db_table': 'Province',
            },
        ),
        migrations.CreateModel(
            name='Region1',
            fields=[
                ('region1_id', models.AutoField(primary_key=True, serialize=False)),
                ('region1_name', models.CharField(max_length=100)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='winesearch.Province')),
            ],
            options={
                'db_table': 'Region1',
            },
        ),
        migrations.CreateModel(
            name='Region2',
            fields=[
                ('region2_id', models.AutoField(primary_key=True, serialize=False)),
                ('region2_name', models.CharField(max_length=100)),
                ('region1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='winesearch.Region1')),
            ],
            options={
                'db_table': 'Region2',
            },
        ),
        migrations.CreateModel(
            name='Taster',
            fields=[
                ('taster_id', models.AutoField(primary_key=True, serialize=False)),
                ('taster_name', models.CharField(max_length=45)),
                ('twitter_handles', models.CharField(blank=True, max_length=45, null=True)),
                ('points', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'Taster',
            },
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('variety_id', models.AutoField(primary_key=True, serialize=False)),
                ('variety_name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'Variety',
            },
        ),
        migrations.CreateModel(
            name='VarietyRegion1',
            fields=[
                ('variety_region1_id', models.AutoField(primary_key=True, serialize=False)),
                ('region1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='winesearch.Region1')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='winesearch.Variety')),
            ],
            options={
                'db_table': 'VarietyRegion1',
            },
        ),
        migrations.CreateModel(
            name='VarietyRegion2',
            fields=[
                ('variety_region2_id', models.AutoField(primary_key=True, serialize=False)),
                ('region2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='winesearch.Region2')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='winesearch.Variety')),
            ],
            options={
                'db_table': 'VarietyRegion2',
            },
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('wine_id', models.AutoField(primary_key=True, serialize=False)),
                ('wine', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='winesearch.Country')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='winesearch.Province')),
                ('region1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='winesearch.Region1')),
                ('region2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='winesearch.Region2')),
                ('variety', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='winesearch.Variety')),
            ],
            options={
                'db_table': 'Wine',
            },
        ),
        migrations.CreateModel(
            name='Winery',
            fields=[
                ('winery_id', models.AutoField(primary_key=True, serialize=False)),
                ('winery_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Winery',
            },
        ),
        migrations.CreateModel(
            name='WineryVariety',
            fields=[
                ('winery_variety_id', models.AutoField(primary_key=True, serialize=False)),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='winesearch.Variety')),
                ('winery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='winesearch.Winery')),
            ],
            options={
                'db_table': 'WineryVariety',
            },
        ),
        migrations.CreateModel(
            name='WineTaster',
            fields=[
                ('wine_taster_id', models.AutoField(primary_key=True, serialize=False)),
                ('taster', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_taster', to='winesearch.Taster')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='winesearch.Wine')),
            ],
            options={
                'db_table': 'WineTaster',
            },
        ),
        migrations.AddField(
            model_name='wine',
            name='winery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='winesearch.Winery'),
        ),
        migrations.AlterUniqueTogether(
            name='region2',
            unique_together={('region1', 'region2_name')},
        ),
        migrations.AlterUniqueTogether(
            name='region1',
            unique_together={('province', 'region1_name')},
        ),
        migrations.AlterUniqueTogether(
            name='province',
            unique_together={('country', 'province_name')},
        ),
    ]
