# Generated by Django 2.1.3 on 2018-12-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winesearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region1',
            name='region1_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='region2',
            name='region2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
