# Generated by Django 2.1.3 on 2018-12-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winesearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wine',
            options={'managed': False, 'ordering': ['wine'], 'verbose_name': 'Wine', 'verbose_name_plural': 'Wines'},
        ),
        migrations.AddField(
            model_name='variety',
            name='region1',
            field=models.ManyToManyField(through='winesearch.VarietyRegion1', to='winesearch.Region1'),
        ),
        migrations.AddField(
            model_name='variety',
            name='region2',
            field=models.ManyToManyField(through='winesearch.VarietyRegion2', to='winesearch.Region2'),
        ),
        migrations.AddField(
            model_name='winery',
            name='variety',
            field=models.ManyToManyField(through='winesearch.WineryVariety', to='winesearch.Variety'),
        ),
        migrations.AlterField(
            model_name='taster',
            name='points',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
