# Generated by Django 2.1.3 on 2018-12-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winesearch', '0003_auto_20181206_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taster',
            name='twitter_handles',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
